# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateField()),
                ('airport_from1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_from1', to='yurjin_tour.Airport')),
                ('airport_from2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_from2', to='yurjin_tour.Airport')),
                ('airport_to1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_to1', to='yurjin_tour.Airport')),
                ('airport_to2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_to2', to='yurjin_tour.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_name', models.CharField(max_length=200)),
                ('tourist_passport', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Office'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Tourist'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Manager'),
        ),
        migrations.AddField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Office'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatory', to='yurjin_tour.Manager'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Status'),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Country'),
        ),
    ]
