# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='input_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Country'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_from1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_from1', to='yurjin_tour.Airport'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_from2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_from2', to='yurjin_tour.Airport'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_to1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_to1', to='yurjin_tour.Airport'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_to2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_to2', to='yurjin_tour.Airport'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Tourist'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Manager'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Office'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatory', to='yurjin_tour.Manager'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Status'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Office'),
        ),
    ]
