# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0003_auto_20161026_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_name',
            new_name='tourist_international_passport',
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist_first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist_international_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist_last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist_mid_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_adddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=200),
        ),
    ]
