# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0004_auto_20161026_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='tourist_first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_international_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_mid_name',
            field=models.CharField(max_length=200),
        ),
    ]
