# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0005_auto_20161026_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.AddField(
            model_name='contract',
            name='tourist_list',
            field=models.ManyToManyField(to='yurjin_tour.Tourist'),
        ),
    ]
