# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0008_contract_contract_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_from1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_from1', to='yurjin_tour.Airport', verbose_name='Аэропорт отправления туда'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_from2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_from2', to='yurjin_tour.Airport', verbose_name='Аэропорт отправления обратно'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_to1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_to1', to='yurjin_tour.Airport', verbose_name='Аэропорт прибытия туда'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='airport_to2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_to2', to='yurjin_tour.Airport', verbose_name='Аэропорт прибытия обратно'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Tourist', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='conclusion_date',
            field=models.DateField(verbose_name='Дата подписания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_num',
            field=models.IntegerField(verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='input_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Status', verbose_name=''),
        ),
    ]
