# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0009_auto_20161101_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='tourist',
            options={'verbose_name': 'Турист', 'verbose_name_plural': 'Туристы'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatory', to='yurjin_tour.Manager', verbose_name='Подписант'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tourist_list',
            field=models.ManyToManyField(related_name='tourist_list', to='yurjin_tour.Tourist', verbose_name='Список туристов'),
        ),
    ]
