# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0011_contract_contract_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Сумма предоплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Сумма контракта'),
        ),
    ]
