# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0013_auto_20161102_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='tourist_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_international_name',
            field=models.CharField(max_length=200, verbose_name='Имя как в загранпаспорте'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_international_passport',
            field=models.CharField(max_length=200, verbose_name='Загранпаспорт'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_mid_name',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='tourist_passport',
            field=models.CharField(max_length=200, verbose_name='Паспорт РФ'),
        ),
    ]
