# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0015_auto_20161103_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=200, verbose_name='Название')),
                ('resort_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Курорты',
                'verbose_name': 'Курорт',
            },
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200, verbose_name='Название')),
                ('registry_num', models.CharField(max_length=50, verbose_name='Реестровый номер')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращеннное наименование')),
                ('fact_address', models.CharField(max_length=50, verbose_name='Место нахождения')),
                ('post_address', models.CharField(max_length=50, verbose_name='Почтовый адрес')),
                ('www_address', models.CharField(max_length=50, verbose_name='Адрес сайта в сети "Интернет"')),
                ('tourpom_member', models.BooleanField(verbose_name='Является членом ассоциации  "ТУРПОМОЩЬ"')),
                ('inn', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ogrn', models.DecimalField(decimal_places=0, max_digits=13)),
            ],
            options={
                'verbose_name_plural': 'Туроператоры',
                'verbose_name': 'Туроператор',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_begin',
            new_name='tour_begin_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_finish',
            new_name='tour_finish_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='airport_from1',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='airport_from2',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='airport_to1',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='airport_to2',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Tourist', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_num',
            field=models.IntegerField(unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='input_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatory', to='yurjin_tour.Manager', verbose_name='Подписант'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Status', verbose_name=''),
        ),
    ]
