# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0016_auto_20161114_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=10, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='excursion',
            field=models.BooleanField(default=False, verbose_name='Включена экскурсионная программа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='hotel_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата въезда в отель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hotel_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда из отеля'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название отеля'),
        ),
        migrations.AddField(
            model_name='contract',
            name='medical_insurance',
            field=models.BooleanField(default=False, verbose_name='Включена медицинская страховка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='non_departure_insurance',
            field=models.BooleanField(default=False, verbose_name='Включена страховка от невыезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='russian_guide',
            field=models.BooleanField(default=False, verbose_name='Включена встреча и проводы с русскоговорящим гидом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='Включена перевозка наземным транспортом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='visa_support',
            field=models.BooleanField(default=False, verbose_name='Включена визовая поддержка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='tour_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала тура'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tour_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания тура'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='inn',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='ogrn',
            field=models.DecimalField(decimal_places=0, max_digits=13, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='contract',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Board', verbose_name='Тип питания'),
        ),
        migrations.AddField(
            model_name='contract',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.RoomType', verbose_name='Тип номера'),
        ),
    ]
