# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0018_auto_20161115_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Код'),
        ),
    ]
