# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0020_auto_20161115_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
