# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0022_auto_20161115_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='conclusion_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
    ]
