# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0023_auto_20161115_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_num',
            field=models.IntegerField(unique_for_month='contract_date', verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Status', verbose_name='Статус'),
        ),
    ]
