# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0026_contract_tour_orepator'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
    ]
