# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0030_tourist_tourist_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='tourist_birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
