# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0031_auto_20161117_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='tourist_international_passport_date_of_expiry',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 5, 34, 8, 738705, tzinfo=utc), verbose_name='Срок действия загранпаспорта'),
            preserve_default=False,
        ),
    ]
