# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0032_tourist_tourist_international_passport_date_of_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='tour_orepator',
            new_name='tour_operator',
        ),
    ]
