# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0035_auto_20161118_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='prepayment_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Сумма предоплаты'),
        ),
    ]
