# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0038_tourist_full_name_r'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_name_r',
            new_name='full_name_r',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_international_name',
            new_name='international_name',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_international_passport',
            new_name='international_passport',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_international_passport_date_of_expiry',
            new_name='international_passport_date_of_expiry',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist_passport',
            new_name='passport',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='manager',
            name='mid_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='mid_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
    ]
