# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0039_auto_20161118_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroperator',
            name='fact_address',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='post_address',
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='short_name',
        ),
        migrations.AddField(
            model_name='touragency',
            name='fact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место нахождения'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touragency',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=13, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touragency',
            name='post_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое наименование'),
        ),
    ]
