# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0039_auto_20161118_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touroperator',
            old_name='operator_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='touragency',
            name='fact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место нахождения'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touragency',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touragency',
            name='post_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='touragency',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='mid_name',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='mid_name',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='fact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='post_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое наименование'),
        ),
    ]
