# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0043_touragency_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='passort_issued_by',
            field=models.CharField(default=datetime.datetime(2016, 11, 22, 7, 38, 57, 815760, tzinfo=utc), max_length=50, verbose_name='Кем выдан паспорт РФ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 22, 7, 39, 19, 501036, tzinfo=utc), verbose_name='Дата выдачи паспорта РФ'),
            preserve_default=False,
        ),
    ]
