# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0045_auto_20161122_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touragency',
            old_name='phone_num',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='touroperator',
            old_name='phone_num',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='tourist',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport_num',
            field=models.CharField(max_length=200, verbose_name='Номер паспорта РФ'),
        ),
    ]
