# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0046_auto_20161122_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='passort_issued_by',
            new_name='passport_issued_by',
        ),
    ]
