# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0047_auto_20161122_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
