# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0049_auto_20170301_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signatory',
        ),
        migrations.AddField(
            model_name='office',
            name='office_chief_r',
            field=models.CharField(default='asdasdasd', max_length=200, verbose_name='В лице кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatory', to='yurjin_tour.Manager', verbose_name='Подписант'),
        ),
    ]
