# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0050_auto_20170310_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='office_chief_r',
        ),
        migrations.RemoveField(
            model_name='office',
            name='signatory',
        ),
    ]
