# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0052_contract_signatory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_office',
            new_name='office',
        ),
        migrations.AddField(
            model_name='tourist',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
    ]
