# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0053_auto_20170320_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50),
        ),
    ]
