# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0054_auto_20170321_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Сумма платежа')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurjin_tour.Contract')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='payments',
            field=models.ManyToManyField(related_name='payments', to='yurjin_tour.Payment', verbose_name='Платежи'),
        ),
    ]
