# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0057_auto_20170321_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractPayment',
            new_name='Payment',
        ),
    ]
