# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0058_auto_20170321_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payments',
            field=models.ManyToManyField(related_name='payments', to='yurjin_tour.Payment', verbose_name='список платежей'),
        ),
    ]
