# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0059_contract_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='payments',
        ),
    ]
