# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0061_auto_20170322_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='contract_id',
            new_name='contract',
        ),
    ]
