# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0062_auto_20170322_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения'),
        ),
    ]
