# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0063_auto_20170327_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='office',
            name='tour_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.TourAgency'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='touragency',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Manager', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
    ]
