# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0064_auto_20170327_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма оплаты',
                'verbose_name_plural': 'Формы оплаты',
            },
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Код IATA'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_num',
            field=models.IntegerField(editable=False, unique_for_month='contract_date', verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tourist_list',
            field=models.ManyToManyField(blank=True, related_name='tourist_list', to='yurjin_tour.Tourist', verbose_name='Список туристов'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manager',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='office',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together=set([('tour_agency', 'office_name', 'office_city')]),
        ),
        migrations.AlterUniqueTogether(
            name='resort',
            unique_together=set([('country', 'resort_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='tourist',
            unique_together=set([('last_name', 'first_name', 'mid_name', 'passport_num', 'passport_date')]),
        ),
    ]
