# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0065_auto_20170328_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.PaymentMethod', verbose_name='Форма оплаты'),
            preserve_default=False,
        ),
    ]
