# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0066_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='prepayment_sum',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_full_name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
