# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_tour', '0067_auto_20170329_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_num',
            field=models.IntegerField(unique_for_month='contract_date', verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yurjin_tour.Status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
    ]
